# Borrowed from Vapor (https://github.com/qutheory/vapor)
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/tannernelson/933b2904903ed90481d91dd4c6904aa9/raw/801bff213423923da891d9a3a893405d53a4325c/install-swift-linux.sh)"
script:
  # Fetch
  - swift package fetch
  # Build
  - swift build --configuration debug
  - swift build --configuration release
  # Test
  - swift test